# .gitlab-ci.yml
stages:
  - setup
  - build
  # - deploy
default: 
  tags: 
    - mern-stack

variables:
  AWS_DEFAULT_REGION: "us-east-1"  # replace with your AWS region
  

setup:
  stage: setup
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y curl unzip
    - curl -O https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
    - unzip terraform_1.1.0_linux_amd64.zip -d /usr/local/bin/
  script:
    # - echo "Setting up infrastructure using Terraform..."
    - terraform init --reconfigure
    - terraform apply -auto-approve

build:
  stage: build
  image: node:20
  script:
    - echo "Installing dependencies..."
    - npm install 
    - npm run build
  artifacts:
    paths:
      - build/

# deploy:
#   stage: deploy
#   image: node:14
#   script:
#     - echo "$PRIVATE_KEY" > deploy_key.pem
#     - chmod 600 deploy_key.pem
#     - echo "Deploying to EC2..."
#     - scp -i deploy_key.pem -r ./build $SSH_USER@$EC2_INSTANCE_IP:/var/www/html  # adjust path as needed
#     - ssh -i deploy_key.pem $SSH_USER@$EC2_INSTANCE_IP << EOF
#         cd /var/www/html
#         pm2 restart app || pm2 start app.js --name "mern-app"
#       EOF
#   only:
#     - main
